### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by rhornung67** [jeffhammond/dpcpp-tutorial#2]
Link to intro to C++ lambda expressions in RAJA in the README.md file here is broken. The correct URL is: 

https://raja.readthedocs.io/en/main/sphinx/user_guide/tutorial.html#a-little-c-background

**Comment by jeffhammond** [comment]
Did you intend to close?

**Comment by rhornung67** [comment]
Yup. I decided to make a PR and not be lazy.

**Comment by jeffhammond** [comment]
Excellent. Also good since I'm not really maintaining these projects anymore 😉

**Comment by rhornung67** [comment]
No worries. I can't sleep at night if I know that there is a broken link somewhere 😆
